### ISSUE TITLE
Opera Browser已被奇虎360及昆侖萬維收購

### ISSUE THREAD

**Issue by zaluvax** [RedDetectorDev/RedDetector#1]
去年由中國奇虎360與昆侖萬維 (Kunlun)在內成員，以6億美元價格收購擁有Opera、Opera Mini，以及Skyfire與Rocket Optimizer在內瀏覽器事業的Opera Software AS。

Source:
https://udn.com/news/story/7086/2884824

**Comment by RedDetectorDev** [comment]
Many thanks!

Added in b3ff606
