### ISSUE TITLE
匪語list建議

### ISSUE THREAD

**Issue by bamami2018** [RedDetectorDev/RedDetector#2]
遺漏蝗語(附上香港用語)
芯片>晶片 
顯卡>顯示卡
手機>手提電話/電話
質量(quality)>質素
充電>叉電
充值>增值
屏幕>螢幕

可能唔係蝗語
搶包山活動
70年代報紙大多使用搶包山一詞 - https://holland.pk/bstyq53g

蹊蹺-蹺蹊
前者主要用於書面語 後者主要用於粵語
而文言文主要使用前者
當年香港報紙兩者皆有使用
https://holland.pk/d35s6wb0
https://holland.pk/4587wg9x

**Comment by RedDetectorDev** [comment]
「手機」好常用喎（而且應該用咗好耐），真係匪語嚟？
「質量」應該係書面語多過匪語，yes?

**Comment by bamami2018** [comment]
手機都算係有爭議性嘅 係高登連登成日都有人講呢個係蝗語 但呢個term依家都算主流
而手提電話九十年代先至開始普及 所以都幾難界定係咪由大陸傳入黎定係約定俗定咁演變

質量 港台通常指mass 而大陸就兼具mass同quallity嘅意思
http://blog.udn.com/ansercomtw/19709928
https://zh.wikipedia.org/zh-hk/品質

**Comment by RedDetectorDev** [comment]
咁我唔add手機住啦

質量 都係skip住先，因爲電腦detect唔到context...

**Comment by RedDetectorDev** [comment]
159dc7c
